### ISSUE TITLE
Youtube track search could be improved

### ISSUE THREAD

**Issue by gordielachance** [tchapi/tuneefy2#2]
https://github.com/tchapi/tuneefy2/blob/5196b27f92bcbe235220d3c6acec29c23701ac91/src/tuneefy/Platform/Platforms/YoutubePlatform.php#L112

Hi, I see you only validate Youtube results if the title looks like this:
**ARTIST - TITLE [Official Video]**

I know there is no perfect way to grab tracks on Youtube, but I think this is completely inconsistent.
This code should be improved; eventually by looping through (a lot of) more schemes.

eg. what if the video title is **ARTIST - TITLE (Official)**, or **ARTIST - TITLE (CLIP OFFICIEL)**

+ it make not real sense to filter official videos since you don't do it with the Soundcloud Platform.

Maybe
* [check that the video category is 10](https://stackoverflow.com/a/34352150/782013) (music video) ?
* check that the video author is an "official" account ?
* have a parameter to let user choose if we want to have those strict filters on the results returned

?

Thanks !

**Comment by tchapi** [comment]
Hello,

Thanks a lot for your feedback and interest.

Video category is already enforced : 

https://github.com/tchapi/tuneefy2/blob/5196b27f92bcbe235220d3c6acec29c23701ac91/src/tuneefy/Platform/Platforms/YoutubePlatform.php#L43

As for the title filter, yes, it could benefit from some review. It boils down to this regex in fact : 

    "/(?P<title>.*)[\(\[](.*official.*video.*)[\)\]]/iu"

https://github.com/tchapi/tuneefy2/blob/5196b27f92bcbe235220d3c6acec29c23701ac91/src/tuneefy/Platform/Platforms/YoutubePlatform.php#L119

That, at the moment, only validates on "Official video" (https://regex101.com/r/VMAkIT/1). My primary concern at the time was to avoid false positives.

I'm not very _Youtube-savvy_ as for what people generally put as titles for their music videos but I'm happy to accept a PR if you want to give it a go. I'm not a fan of checking if the account is "official" since that would make us do a supplementary API call (I think). As for the parameter, we already have such a paradigm, so you could change the regex depending on the value of the `mode` or  `aggressive` parameters for instance.

What do you think ?

**Comment by gordielachance** [comment]
Hi, I understand your concern.
And of course, more API calls would slow the Tuneefy.

Currently I almost never get Youtube results, while there are plenty positive results while doing a Youtube search...

And I did implement your API just for that : get Youtube (and SoundCloud) matches; other providers are not useful in my script.  
So my current implementation is almost worthless :/

Maybe you could compare the input string with the returned result title; and extract a score from that (there is a function that could maybe do that, [similar_text()](http://php.net/manual/fr/function.similar-text.php) )
Then your API would; by default, eliminate results below x %; and users of the API could choose their own % limit if they want to filter the results by themselves.

Anyway this is urgent to do something about that.  
Your API is really nice and there is no (free) equivalent products out there; but this is IMO a big issue...

Would you help me ? :)

**Comment by gordielachance** [comment]
What do u think of it ?

**Comment by tchapi** [comment]
The regex can be improved, as previously explained, and that would likely improve the results (but with more false positives, too — you don't realize how many people use ARTIST - TITLE for their cover, or a capella version of a known song).

Creating a specific filter for Youtube in the API parameters defeats the purpose of the whole API, so I'm not in favour of doing so. Google does not provide a proper API for music videos, and this is the real problem here; I don't think tuneefy can (or should) bridge this gap in an efficient manner.

I'll give a try to the regex in the coming weeks when I find the time and keep you updated..

**Comment by gordielachance** [comment]
Yes, I can understand that; of course I never saw an efficient way of getting a specific track on Youtube.

For what I see, there are 
* services who offers a reliable way to search a track (by artist, title, etc. - like Spotify, or Musicbrainz, etc); 
* services that just offers a "basic" search, like Youtube or Soundcloud.  They won't detect fan covers, lives, remixes, (of course they are, but they don't give us that information:)) - you can never be sure to get the right track.

But there could be a parameter for that.  
By default, you won't list those suspicious results, but an API user could get them if he want to; by adding a parameter (eg. &filters={"youtube":false,"soundcloud":false})

I would love to use your API, but for what I need it is currently too restrictive.
Let me know if you totally disagree with that idea or if we could discuss about it :)

Thanks!

**Comment by gordielachance** [comment]
About the regexes, maybe you can recycle some ideas from the [Youtube Tomahawk resolver](https://github.com/tomahawk-player/tomahawk-resolvers/blob/master/youtube/content/contents/code/youtube.js#L578).

**Comment by gordielachance** [comment]
and so ?  Not interested ?
Thanks

**Comment by tchapi** [comment]
Sorry but unfortunately I haven't had the ability to dedicate time to this so far — again you can submit a PR if you want to have a go at the Tomahawk regex (that seems quite good)

**Comment by tchapi** [comment]
New Youtube Regex merged and deployed
