### ISSUE TITLE
Allow to disable regex filters ?

### ISSUE THREAD

**Issue by gordielachance** [tchapi/tuneefy2#5]
Hi !

I still think that your API is really wonderful but lacks a way to retrieve "raw" results / disable filters (an extra parameter in the API request?).
it's not easy to improve regexes and maybe it is anyway utopical... 
But with your current API, you miss potential users (like me) who might be interested by an API that would fetch results from various services, not (so) strictly filtered.

Any chance to consider it ?

Thanks !

B

PS : eg. my website [Spiff-Radio.org](http://www.spiff-radio.org/wpsstm_live_playlist/alternativeradio/) currently uses Tuneefy to play songs, but misses a LOT of tracks while they are on Youtube.  I would personnally prefer a false positive (a remix, etc etc) than nothing...

**Comment by tchapi** [comment]
Hi

The main goal of tuneefy is aggregating results from different streaming platforms.
Some platforms have a well-behaved API (_let's take Spotify for instance, or Deezer_) that have rich and coherent pieces of metadata, and some have not (_Youtube, Soundcloud, ..._), so trying to merge data from Youtube or Soundcloud is somehow a _hack_, since the level of detail needed to aggregate songs from different platforms is high and that these platforms do not provide it — so I have to resort to filters / regex / etc to try to compensate. This is clearly not ideal, maybe utopical, but it's, to date, the only way I have found.

If you need a raw stream of data from one of these platforms, then I think you don't really need tuneefy. You will be better off by just calling the Youtube or Soundclound API directly and maybe agreggating the results afterwards with your own rules.

I could theoretically do this on tuneefy's side, but that would need to be a different endpoint, and moreover the computational cost to get 10x more results from each platform would be far too high and would make the api unusable (_and so far I don't have any time to dedicate to a modification that could be quite big_).

If you want to capitalise upon the work that has been done on the API side, I'd recommend you fork the project and tailor it to suit your needs; it's pretty easy to setup (a simple mysql / php stack is sufficient) and you can have your own tuneefy instance running privately, where you can add/remove the platforms that you want to use.

Best !
